# Generated by Django 6.0.2 on 2026-05-05 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='agile_practices',
            field=models.CharField(blank=True, help_text='Scrum, Kanban, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='concurrent_projects',
            field=models.IntegerField(default=0, help_text='Number of concurrent projects'),
        ),
        migrations.AddField(
            model_name='team',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='development_focus',
            field=models.TextField(blank=True, help_text='Development focus areas'),
        ),
        migrations.AddField(
            model_name='team',
            name='jira_board_link',
            field=models.URLField(blank=True, help_text='Link to Jira board'),
        ),
        migrations.AddField(
            model_name='team',
            name='jira_project_name',
            field=models.CharField(blank=True, help_text='Jira project name', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='workstream',
            field=models.CharField(blank=True, help_text='Workstream (MF)', max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(help_text='Team mission and responsibilities'),
        ),
    ]
