# Generated by Django 6.0.2 on 2026-05-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
