# Generated by Django 6.0.4 on 2026-05-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_delete_dependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtype',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon class', max_length=50),
        ),
    ]
